name: form_shield
description: A declarative, rule-based form validation library for Flutter apps. Supports async validation, custom validation logic, and more.
version: 0.5.0
homepage: https://github.com/stevenosse/form_shield
issue_tracker: https://github.com/stevenosse/form_shield/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

