name: form_shield
description: A declarative, rule-based form validation library for Flutter apps. Supports async validation, custom validation logic, and more.
version: 0.10.0
homepage: https://github.com/stevenosse/form_shield
issue_tracker: https://github.com/stevenosse/form_shield/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.14

flutter_intl:
  enabled: true
  class_name: FormShieldI18n
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/src/generated
